<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!-- Test names and xUnit's conventions don't need XML docs. -->
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CA1707;CA1515;CA1861;CA2007</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Garage.App.Core\Garage.App.Core.csproj" />
    <ProjectReference Include="..\..\src\Garage.Grpc\Garage.Grpc.csproj" />
  </ItemGroup>

</Project>
