"""Bazel builds of the winapp/ projects, compiled as the .NET SDK compiles them.

Each csproj stays the source of truth (Visual Studio, `dotnet build`, the Windows CI job); a
project's BUILD.bazel mirrors it through these macros, and //winapp:csproj_sync_test holds the two
together. The settings Directory.Build.props gives every project are applied here, matched to the
`csc` command line MSBuild runs:

- net10.0, C# `latest`, nullable enabled, XML docs, warnings as errors at warning level 10
  (AnalysisLevel=latest), CS1701/CS1702/CS8002 off as the SDK has them;
- the SDK's implicit `global using`s (ImplicitUsings), and the AssemblyInfo it generates, so
  `Assembly.GetName().Version` reads 1.0.0.0 under either build;
- a net10.0-windows project (`windows = True`) is compiled as net10.0 with the
  TargetPlatform/SupportedOSPlatform attributes the SDK adds for it. rules_dotnet has no
  net10.0-windows framework, and none of these projects uses the Windows Desktop pack, so the
  references are the same.

Not carried over: the SDK's own analyzers (NetAnalyzers and the IDE code-style rules that
AnalysisLevel and EnforceCodeStyleInBuild turn on). Analyzers shipped in the targeting pack
(LibraryImport, JSON and Regex generators) and in NuGet packages (CommunityToolkit.Mvvm's
generators, xunit.analyzers) do run. `dotnet build` remains the analyzer gate.
"""

load("@rules_dotnet//dotnet:defs.bzl", "csharp_binary", "csharp_library", "csharp_test")

_COMMON = {
    "generate_documentation_file": True,
    "langversion": "latest",
    "nullable": "enable",
    "target_frameworks": ["net10.0"],
    "treat_warnings_as_errors": True,
}

# The SDK's /nowarn; a project's own NoWarn adds to it.
_SDK_NOWARN = ["CS1701", "CS1702", "CS8002"]

# After the rule's own /warn:<level> (0 to 5 only), so the SDK's level 10 wins.
_COMPILER_OPTIONS = ["/warn:10"]

def _assembly_info(name, assembly_name, windows, test):
    """The AssemblyInfo.cs the SDK generates for a project, as a source file."""
    lines = [
        "// Generated by //winapp/bazel:defs.bzl, as the .NET SDK generates AssemblyInfo.cs.",
        '[assembly: System.Reflection.AssemblyCompanyAttribute("Garage")]',
        '[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]',
        '[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]',
        '[assembly: System.Reflection.AssemblyProductAttribute("Garage")]',
        '[assembly: System.Reflection.AssemblyTitleAttribute("%s")]' % assembly_name,
        '[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]',
        '[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETCoreApp,Version=v10.0", FrameworkDisplayName = ".NET 10.0")]',
    ]
    if test:
        lines.append('[assembly: System.Reflection.AssemblyMetadata("Microsoft.Testing.Platform.Application", "true")]')
    if windows:
        lines += [
            '[assembly: System.Runtime.Versioning.TargetPlatformAttribute("Windows7.0")]',
            '[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("Windows7.0")]',
        ]
    out = name + ".AssemblyInfo.cs"
    native.genrule(
        name = name + "_assembly_info",
        outs = [out],
        cmd = "cat > $@ <<'EOF'\n%s\nEOF" % "\n".join(lines),
    )
    return [":" + out]

def _sync_files(name):
    """The csproj and BUILD.bazel //winapp/bazel:csproj_sync_test compares."""
    native.filegroup(
        name = "csproj_sync",
        srcs = ["BUILD.bazel", name + ".csproj"],
        visibility = ["//winapp/bazel:__pkg__"],
    )

def _srcs(srcs):
    # A project's bin/ and obj/ hold the .NET SDK build's output, generated sources included.
    if srcs == None:
        srcs = native.glob(["**/*.cs"], exclude = ["bin/**", "obj/**"])
    return srcs

def garage_csharp_library(name, srcs = None, windows = False, nowarn = [], **kwargs):
    """A class library project (Microsoft.NET.Sdk, no OutputType)."""
    _sync_files(name)
    csharp_library(
        name = name,
        srcs = _srcs(srcs) + ["//winapp/bazel:GlobalUsings.cs"] + _assembly_info(name, name, windows, False),
        nowarn = _SDK_NOWARN + nowarn,
        compiler_options = _COMPILER_OPTIONS,
        **(_COMMON | kwargs)
    )

def garage_csharp_binary(name, srcs = None, windows = False, nowarn = [], **kwargs):
    """An `OutputType=Exe` project."""
    _sync_files(name)
    csharp_binary(
        name = name,
        srcs = _srcs(srcs) + ["//winapp/bazel:GlobalUsings.cs"] + _assembly_info(name, name, windows, False),
        nowarn = _SDK_NOWARN + nowarn,
        compiler_options = _COMPILER_OPTIONS,
        **(_COMMON | kwargs)
    )

def garage_xunit_test(name, srcs = None, windows = False, nowarn = [], deps = [], **kwargs):
    """An xunit.v3 test project, run by xunit's in-process console runner.

    The SDK build generates the entry point (xunit.v3's targets) and `global using Xunit`
    (the project's <Using>); //winapp/bazel supplies both.

    A net10.0-windows test project (`windows = True`) calls Windows APIs (kernel32, advapi32, the
    Credential Manager) and expects Windows paths, so its test runs only on Windows. Everywhere
    else `<name>_compile` builds the same sources as a library under the same assembly name, so a
    Mac or Linux build still compiles every line of it.
    """
    _sync_files(name)
    srcs = _srcs(srcs) + [
        "//winapp/bazel:GlobalUsings.cs",
        "//winapp/bazel:XunitGlobalUsings.cs",
    ] + _assembly_info(name, name, windows, True)
    deps = deps + ["@winapp_nuget//xunit.v3"]
    common = _COMMON | {
        # Test names and xUnit's conventions need no XML docs (the test projects' setting).
        "generate_documentation_file": False,
    }
    csharp_test(
        name = name,
        srcs = srcs + ["//winapp/bazel:XunitEntryPoint.cs"],
        nowarn = _SDK_NOWARN + nowarn,
        compiler_options = _COMPILER_OPTIONS,
        deps = deps,
        target_compatible_with = ["@platforms//os:windows"] if windows else [],
        **(common | kwargs)
    )
    if windows:
        csharp_library(
            name = name + "_compile",
            out = name,
            srcs = srcs,
            nowarn = _SDK_NOWARN + nowarn,
            compiler_options = _COMPILER_OPTIONS,
            deps = deps,
            testonly = True,
            **(common | kwargs)
        )
