#!/usr/bin/env python3
"""Regenerate winapp/nuget.bzl: every NuGet package the Bazel-built winapp projects use, pinned.

Directory.Packages.props is the only place a version is written. This restores the projects
Bazel builds with the .NET SDK, reads each one's ``obj/project.assets.json`` (which holds the
whole resolved graph, with every package's sha512), and writes the ``nuget_repo`` that
rules_dotnet fetches them through. Run it after changing a package version or reference:

    python3 winapp/bazel/repin.py              # restore, then write winapp/nuget.bzl
    python3 winapp/bazel/repin.py --no-restore # reuse the last restore's assets files

The projects are Garage.slnx's less Garage.App and Garage.App.UITests, which Bazel does not build
(WinUI's XAML compiler and FlaUI run only on Windows), so their packages (the Windows App SDK,
H.NotifyIcon, FlaUI) never enter the pins.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

from projects import bazel_projects

REPO = Path(__file__).resolve().parents[2]
WINAPP = REPO / "winapp"
OUT = WINAPP / "nuget.bzl"

NUGET_ORG = "https://api.nuget.org/v3/index.json"

# Bazel builds every project as net10.0 (rules_dotnet has no net10.0-windows), and the package
# targets select their dependencies on the framework of whatever depends on them, so each
# package carries one list under each framework a consumer can be built for.
FRAMEWORKS = ["net10.0", "netstandard2.0"]


def restore(projects: list[str]) -> None:
    for project in projects:
        # The net10.0-windows projects restore off Windows only with Windows targeting enabled.
        subprocess.run(
            ["dotnet", "restore", project, "-p:EnableWindowsTargeting=true", "-v:q"],
            cwd=WINAPP,
            check=True,
        )


def download_sha512(package_folders: list[Path], path: str, package_id: str, version: str) -> str:
    """The sha512 of the .nupkg as nuget.org serves it, which is what Bazel checks.

    Not the assets file's ``sha512``: that is NuGet's contentHash, taken without the repository
    signature nuget.org adds, so it never matches the downloaded file. The restore leaves the
    download's own hash beside the package in the global packages folder.
    """
    name = f"{package_id.lower()}.{version.lower()}.nupkg.sha512"
    for folder in package_folders:
        candidate = folder / path / name
        if candidate.is_file():
            return candidate.read_text().strip()
    sys.exit(f"no {name} under {', '.join(map(str, package_folders))}; run without --no-restore")


def collect(projects: list[str]) -> list[dict]:
    packages: dict[str, dict] = {}
    for project in projects:
        assets = json.loads((WINAPP / project / "obj" / "project.assets.json").read_text())
        libraries = assets["libraries"]
        package_folders = [Path(folder) for folder in assets["packageFolders"]]
        for target in assets["targets"].values():
            for key, entry in target.items():
                if entry.get("type") != "package":
                    continue
                package_id, version = key.split("/")
                known = packages.get(package_id.lower())
                if known and known["version"] != version:
                    sys.exit(
                        f"{package_id} resolves to {known['version']} in one project and {version} in "
                        f"{project}; pin it in Directory.Packages.props so every project agrees"
                    )
                deps = sorted(entry.get("dependencies", {}), key=str.lower)
                if known:
                    known["deps"] = sorted(set(known["deps"]) | set(deps), key=str.lower)
                    continue
                packages[package_id.lower()] = {
                    "id": package_id,
                    "version": version,
                    "sha512": "sha512-" + download_sha512(package_folders, libraries[key]["path"], package_id, version),
                    "deps": deps,
                }
    return [packages[k] for k in sorted(packages)]


def render(packages: list[dict]) -> str:
    lines = [
        '"""GENERATED by winapp/bazel/repin.py from the projects\' project.assets.json. Do not edit."""',
        "",
        'load("@rules_dotnet//dotnet:defs.bzl", "nuget_repo")',
        "",
        "def winapp_nuget_packages():",
        '    """Declares @winapp_nuget, one target per package (@winapp_nuget//<id lowercased>)."""',
        "    nuget_repo(",
        '        name = "winapp_nuget",',
        "        packages = [",
    ]
    for package in packages:
        entry = {
            "name": package["id"],
            "id": package["id"],
            "version": package["version"],
            "sha512": package["sha512"],
            "sources": [NUGET_ORG],
            "dependencies": {framework: package["deps"] for framework in FRAMEWORKS},
            "targeting_pack_overrides": [],
            "framework_list": [],
            "tools": {},
        }
        lines.append(f"            {json.dumps(entry)},")
    lines += ["        ],", "    )", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--no-restore", action="store_true", help="Reuse the existing project.assets.json files.")
    args = parser.parse_args()
    projects = bazel_projects(WINAPP)
    if not args.no_restore:
        restore(projects)
    packages = collect(projects)
    OUT.write_text(render(packages))
    print(f"wrote {OUT.relative_to(REPO)}: {len(packages)} packages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
