// The entry point of each Bazel-built test project. The .NET SDK build generates xunit.v3's own
// (XunitAutoGeneratedEntryPoint.cs), which runs this same in-process console runner whenever
// Microsoft.Testing.Platform did not start it; Bazel reads the exit code and test.log.
namespace Garage.Bazel;

[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
internal static class XunitEntryPoint
{
    public static int Main(string[] args) =>
        Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult();
}
