//===----------------------------------------------------------------------===//
// Garage: link-time binding for PythonKit (ext/pythonkit/PythonKit, a submodule).
// Generated by tools/pythonkit/generate_symbols.py; do not edit.
//
// Upstream PythonKit dlopen()s the Python library and dlsym()s every C-API
// function it calls. Garage always links the bundled Python.framework, so this
// replaces PythonLibrary.swift and PythonLibrary+Symbols.swift: each symbol is a
// plain C function here, resolved by the static linker and bound by dyld at load
// time, with no dlopen or dlsym.
//===----------------------------------------------------------------------===//

#include <Python.h>

#include "GaragePythonKitSymbols.h"

void GaragePyKit_Py_Initialize(void) { Py_Initialize(); }
void GaragePyKit_Py_IncRef(void *_Nullable a0) { Py_IncRef(a0); }
void GaragePyKit_Py_DecRef(void *_Nullable a0) { Py_DecRef(a0); }
void *_Nullable GaragePyKit_PyImport_ImportModule(const char *_Nonnull a0) { return PyImport_ImportModule(a0); }
void *_Nonnull GaragePyKit_PyEval_GetBuiltins(void) { return PyEval_GetBuiltins(); }
void GaragePyKit_PyRun_SimpleString(const char *_Nonnull a0) { PyRun_SimpleString(a0); }
void *_Nonnull GaragePyKit_PyCFunction_NewEx(void *_Nonnull a0, void *_Nonnull a1, void *_Nullable a2) { return PyCFunction_NewEx(a0, a1, a2); }
void *_Nonnull GaragePyKit_PyInstanceMethod_New(void *_Nonnull a0) { return PyInstanceMethod_New(a0); }
void *_Nonnull GaragePyKit_PyCapsule_New(void *_Nonnull a0, const char *_Nullable a1, struct GaragePyKitOpaque *_Nonnull a2) { return PyCapsule_New(a0, a1, (PyCapsule_Destructor)(void *)a2); }
void *_Nonnull GaragePyKit_PyCapsule_GetPointer(void *_Nullable a0, const char *_Nullable a1) { return PyCapsule_GetPointer(a0, a1); }
void GaragePyKit_PyErr_SetString(void *_Nonnull a0, const char *_Nullable a1) { PyErr_SetString(a0, a1); }
void *_Nullable GaragePyKit_PyErr_Occurred(void) { return PyErr_Occurred(); }
void GaragePyKit_PyErr_Clear(void) { PyErr_Clear(); }
void GaragePyKit_PyErr_Fetch(void *_Nullable *_Nonnull a0, void *_Nullable *_Nonnull a1, void *_Nullable *_Nonnull a2) { PyErr_Fetch((PyObject **)a0, (PyObject **)a1, (PyObject **)a2); }
void *_Nullable GaragePyKit_PyDict_New(void) { return PyDict_New(); }
int GaragePyKit_PyDict_Contains(void *_Nullable a0, void *_Nullable a1) { return PyDict_Contains(a0, a1); }
void GaragePyKit_PyDict_SetItem(void *_Nullable a0, void *_Nonnull a1, void *_Nonnull a2) { PyDict_SetItem(a0, a1, a2); }
void *_Nullable GaragePyKit_PyObject_GetItem(void *_Nonnull a0, void *_Nonnull a1) { return PyObject_GetItem(a0, a1); }
void GaragePyKit_PyObject_SetItem(void *_Nonnull a0, void *_Nonnull a1, void *_Nonnull a2) { PyObject_SetItem(a0, a1, a2); }
void GaragePyKit_PyObject_DelItem(void *_Nonnull a0, void *_Nonnull a1) { PyObject_DelItem(a0, a1); }
void *_Nullable GaragePyKit_PyObject_Call(void *_Nonnull a0, void *_Nonnull a1, void *_Nullable a2) { return PyObject_Call(a0, a1, a2); }
void *_Nullable GaragePyKit_PyObject_CallObject(void *_Nonnull a0, void *_Nonnull a1) { return PyObject_CallObject(a0, a1); }
void *_Nullable GaragePyKit_PyObject_GetAttrString(void *_Nonnull a0, const char *_Nonnull a1) { return PyObject_GetAttrString(a0, a1); }
int GaragePyKit_PyObject_SetAttrString(void *_Nonnull a0, const char *_Nonnull a1, void *_Nonnull a2) { return PyObject_SetAttrString(a0, a1, a2); }
void *_Nullable GaragePyKit_PySlice_New(void *_Nullable a0, void *_Nullable a1, void *_Nullable a2) { return PySlice_New(a0, a1, a2); }
void *_Nullable GaragePyKit_PyTuple_New(long a0) { return PyTuple_New(a0); }
void GaragePyKit_PyTuple_SetItem(void *_Nonnull a0, long a1, void *_Nonnull a2) { PyTuple_SetItem(a0, a1, a2); }
void *_Nullable GaragePyKit_PyObject_RichCompare(void *_Nonnull a0, void *_Nonnull a1, int a2) { return PyObject_RichCompare(a0, a1, a2); }
int GaragePyKit_PyObject_RichCompareBool(void *_Nonnull a0, void *_Nonnull a1, int a2) { return PyObject_RichCompareBool(a0, a1, a2); }
int GaragePyKit_PyDict_Next(void *_Nonnull a0, long *_Nonnull a1, void *_Nullable *_Nonnull a2, void *_Nullable *_Nonnull a3) { return PyDict_Next(a0, (Py_ssize_t *)a1, (PyObject **)a2, (PyObject **)a3); }
void *_Nullable GaragePyKit_PyIter_Next(void *_Nonnull a0) { return PyIter_Next(a0); }
void *_Nullable GaragePyKit_PyObject_GetIter(void *_Nonnull a0) { return PyObject_GetIter(a0); }
void *_Nullable GaragePyKit_PyList_New(long a0) { return PyList_New(a0); }
int GaragePyKit_PyList_SetItem(void *_Nonnull a0, long a1, void *_Nonnull a2) { return PyList_SetItem(a0, a1, a2); }
void *_Nonnull GaragePyKit_PyBool_FromLong(long a0) { return PyBool_FromLong(a0); }
double GaragePyKit_PyFloat_AsDouble(void *_Nonnull a0) { return PyFloat_AsDouble(a0); }
void *_Nonnull GaragePyKit_PyFloat_FromDouble(double a0) { return PyFloat_FromDouble(a0); }
long GaragePyKit_PyInt_AsLong(void *_Nonnull a0) { return PyLong_AsLong(a0); }
void *_Nonnull GaragePyKit_PyInt_FromLong(long a0) { return PyLong_FromLong(a0); }
unsigned long GaragePyKit_PyInt_AsUnsignedLongMask(void *_Nonnull a0) { return PyLong_AsUnsignedLongMask(a0); }
void *_Nonnull GaragePyKit_PyInt_FromSize_t(unsigned long a0) { return PyLong_FromUnsignedLong(a0); }
const char *_Nullable GaragePyKit_PyString_AsString(void *_Nonnull a0) { return PyUnicode_AsUTF8(a0); }
void *_Nullable GaragePyKit_PyString_FromStringAndSize(const char *_Nullable a0, long a1) { return PyUnicode_DecodeUTF8(a0, a1, NULL); }
void *_Nullable GaragePyKit_PyBytes_FromStringAndSize(const char *_Nullable a0, long a1) { return PyBytes_FromStringAndSize(a0, a1); }
int GaragePyKit_PyBytes_AsStringAndSize(void *_Nonnull a0, char *_Nullable *_Nullable a1, long *_Nullable a2) { return PyBytes_AsStringAndSize(a0, a1, (Py_ssize_t *)a2); }
void *_Nullable GaragePyKit_PyNumber_Add(void *_Nullable a0, void *_Nullable a1) { return PyNumber_Add(a0, a1); }
void *_Nullable GaragePyKit_PyNumber_Subtract(void *_Nullable a0, void *_Nullable a1) { return PyNumber_Subtract(a0, a1); }
void *_Nullable GaragePyKit_PyNumber_Multiply(void *_Nullable a0, void *_Nullable a1) { return PyNumber_Multiply(a0, a1); }
void *_Nullable GaragePyKit_PyNumber_TrueDivide(void *_Nullable a0, void *_Nullable a1) { return PyNumber_TrueDivide(a0, a1); }
void *_Nullable GaragePyKit_PyNumber_InPlaceAdd(void *_Nullable a0, void *_Nullable a1) { return PyNumber_InPlaceAdd(a0, a1); }
void *_Nullable GaragePyKit_PyNumber_InPlaceSubtract(void *_Nullable a0, void *_Nullable a1) { return PyNumber_InPlaceSubtract(a0, a1); }
void *_Nullable GaragePyKit_PyNumber_InPlaceMultiply(void *_Nullable a0, void *_Nullable a1) { return PyNumber_InPlaceMultiply(a0, a1); }
void *_Nullable GaragePyKit_PyNumber_InPlaceTrueDivide(void *_Nullable a0, void *_Nullable a1) { return PyNumber_InPlaceTrueDivide(a0, a1); }
void *_Nullable GaragePyKit_PyNumber_Negative(void *_Nullable a0) { return PyNumber_Negative(a0); }
void *_Nullable GaragePyKit_PyNumber_And(void *_Nullable a0, void *_Nullable a1) { return PyNumber_And(a0, a1); }
void *_Nullable GaragePyKit_PyNumber_Or(void *_Nullable a0, void *_Nullable a1) { return PyNumber_Or(a0, a1); }
void *_Nullable GaragePyKit_PyNumber_Xor(void *_Nullable a0, void *_Nullable a1) { return PyNumber_Xor(a0, a1); }
void *_Nullable GaragePyKit_PyNumber_InPlaceAnd(void *_Nullable a0, void *_Nullable a1) { return PyNumber_InPlaceAnd(a0, a1); }
void *_Nullable GaragePyKit_PyNumber_InPlaceOr(void *_Nullable a0, void *_Nullable a1) { return PyNumber_InPlaceOr(a0, a1); }
void *_Nullable GaragePyKit_PyNumber_InPlaceXor(void *_Nullable a0, void *_Nullable a1) { return PyNumber_InPlaceXor(a0, a1); }
void *_Nullable GaragePyKit_PyNumber_Invert(void *_Nullable a0) { return PyNumber_Invert(a0); }

void *_Nonnull GaragePyKit__Py_ZeroStruct(void) { return Py_False; }
void *_Nonnull GaragePyKit__Py_TrueStruct(void) { return Py_True; }
void *_Nonnull GaragePyKit_PyBool_Type(void) { return (void *)&PyBool_Type; }
void *_Nonnull GaragePyKit_PySlice_Type(void) { return (void *)&PySlice_Type; }
