//===----------------------------------------------------------------------===//
// Garage: link-time binding for PythonKit (ext/pythonkit/PythonKit, a submodule).
// Generated by tools/pythonkit/generate_symbols.py; do not edit.
//
// Upstream PythonKit dlopen()s the Python library and dlsym()s every C-API
// function it calls. Garage always links the bundled Python.framework, so this
// replaces PythonLibrary.swift and PythonLibrary+Symbols.swift: each symbol is a
// plain C function here, resolved by the static linker and bound by dyld at load
// time, with no dlopen or dlsym.
//===----------------------------------------------------------------------===//

#ifndef GARAGE_PYTHONKIT_SYMBOLS_H
#define GARAGE_PYTHONKIT_SYMBOLS_H

// The types are PythonKit's (opaque pointers), not CPython's, so this header never
// includes Python.h and nothing that imports it sees CPython's own declarations.

struct GaragePyKitOpaque;

void GaragePyKit_Py_Initialize(void);
void GaragePyKit_Py_IncRef(void *_Nullable a0);
void GaragePyKit_Py_DecRef(void *_Nullable a0);
void *_Nullable GaragePyKit_PyImport_ImportModule(const char *_Nonnull a0);
void *_Nonnull GaragePyKit_PyEval_GetBuiltins(void);
void GaragePyKit_PyRun_SimpleString(const char *_Nonnull a0);
void *_Nonnull GaragePyKit_PyCFunction_NewEx(void *_Nonnull a0, void *_Nonnull a1, void *_Nullable a2);
void *_Nonnull GaragePyKit_PyInstanceMethod_New(void *_Nonnull a0);
void *_Nonnull GaragePyKit_PyCapsule_New(void *_Nonnull a0, const char *_Nullable a1, struct GaragePyKitOpaque *_Nonnull a2);
void *_Nonnull GaragePyKit_PyCapsule_GetPointer(void *_Nullable a0, const char *_Nullable a1);
void GaragePyKit_PyErr_SetString(void *_Nonnull a0, const char *_Nullable a1);
void *_Nullable GaragePyKit_PyErr_Occurred(void);
void GaragePyKit_PyErr_Clear(void);
void GaragePyKit_PyErr_Fetch(void *_Nullable *_Nonnull a0, void *_Nullable *_Nonnull a1, void *_Nullable *_Nonnull a2);
void *_Nullable GaragePyKit_PyDict_New(void);
int GaragePyKit_PyDict_Contains(void *_Nullable a0, void *_Nullable a1);
void GaragePyKit_PyDict_SetItem(void *_Nullable a0, void *_Nonnull a1, void *_Nonnull a2);
void *_Nullable GaragePyKit_PyObject_GetItem(void *_Nonnull a0, void *_Nonnull a1);
void GaragePyKit_PyObject_SetItem(void *_Nonnull a0, void *_Nonnull a1, void *_Nonnull a2);
void GaragePyKit_PyObject_DelItem(void *_Nonnull a0, void *_Nonnull a1);
void *_Nullable GaragePyKit_PyObject_Call(void *_Nonnull a0, void *_Nonnull a1, void *_Nullable a2);
void *_Nullable GaragePyKit_PyObject_CallObject(void *_Nonnull a0, void *_Nonnull a1);
void *_Nullable GaragePyKit_PyObject_GetAttrString(void *_Nonnull a0, const char *_Nonnull a1);
int GaragePyKit_PyObject_SetAttrString(void *_Nonnull a0, const char *_Nonnull a1, void *_Nonnull a2);
void *_Nullable GaragePyKit_PySlice_New(void *_Nullable a0, void *_Nullable a1, void *_Nullable a2);
void *_Nullable GaragePyKit_PyTuple_New(long a0);
void GaragePyKit_PyTuple_SetItem(void *_Nonnull a0, long a1, void *_Nonnull a2);
void *_Nullable GaragePyKit_PyObject_RichCompare(void *_Nonnull a0, void *_Nonnull a1, int a2);
int GaragePyKit_PyObject_RichCompareBool(void *_Nonnull a0, void *_Nonnull a1, int a2);
int GaragePyKit_PyDict_Next(void *_Nonnull a0, long *_Nonnull a1, void *_Nullable *_Nonnull a2, void *_Nullable *_Nonnull a3);
void *_Nullable GaragePyKit_PyIter_Next(void *_Nonnull a0);
void *_Nullable GaragePyKit_PyObject_GetIter(void *_Nonnull a0);
void *_Nullable GaragePyKit_PyList_New(long a0);
int GaragePyKit_PyList_SetItem(void *_Nonnull a0, long a1, void *_Nonnull a2);
void *_Nonnull GaragePyKit_PyBool_FromLong(long a0);
double GaragePyKit_PyFloat_AsDouble(void *_Nonnull a0);
void *_Nonnull GaragePyKit_PyFloat_FromDouble(double a0);
long GaragePyKit_PyInt_AsLong(void *_Nonnull a0);
void *_Nonnull GaragePyKit_PyInt_FromLong(long a0);
unsigned long GaragePyKit_PyInt_AsUnsignedLongMask(void *_Nonnull a0);
void *_Nonnull GaragePyKit_PyInt_FromSize_t(unsigned long a0);
const char *_Nullable GaragePyKit_PyString_AsString(void *_Nonnull a0);
void *_Nullable GaragePyKit_PyString_FromStringAndSize(const char *_Nullable a0, long a1);
void *_Nullable GaragePyKit_PyBytes_FromStringAndSize(const char *_Nullable a0, long a1);
int GaragePyKit_PyBytes_AsStringAndSize(void *_Nonnull a0, char *_Nullable *_Nullable a1, long *_Nullable a2);
void *_Nullable GaragePyKit_PyNumber_Add(void *_Nullable a0, void *_Nullable a1);
void *_Nullable GaragePyKit_PyNumber_Subtract(void *_Nullable a0, void *_Nullable a1);
void *_Nullable GaragePyKit_PyNumber_Multiply(void *_Nullable a0, void *_Nullable a1);
void *_Nullable GaragePyKit_PyNumber_TrueDivide(void *_Nullable a0, void *_Nullable a1);
void *_Nullable GaragePyKit_PyNumber_InPlaceAdd(void *_Nullable a0, void *_Nullable a1);
void *_Nullable GaragePyKit_PyNumber_InPlaceSubtract(void *_Nullable a0, void *_Nullable a1);
void *_Nullable GaragePyKit_PyNumber_InPlaceMultiply(void *_Nullable a0, void *_Nullable a1);
void *_Nullable GaragePyKit_PyNumber_InPlaceTrueDivide(void *_Nullable a0, void *_Nullable a1);
void *_Nullable GaragePyKit_PyNumber_Negative(void *_Nullable a0);
void *_Nullable GaragePyKit_PyNumber_And(void *_Nullable a0, void *_Nullable a1);
void *_Nullable GaragePyKit_PyNumber_Or(void *_Nullable a0, void *_Nullable a1);
void *_Nullable GaragePyKit_PyNumber_Xor(void *_Nullable a0, void *_Nullable a1);
void *_Nullable GaragePyKit_PyNumber_InPlaceAnd(void *_Nullable a0, void *_Nullable a1);
void *_Nullable GaragePyKit_PyNumber_InPlaceOr(void *_Nullable a0, void *_Nullable a1);
void *_Nullable GaragePyKit_PyNumber_InPlaceXor(void *_Nullable a0, void *_Nullable a1);
void *_Nullable GaragePyKit_PyNumber_Invert(void *_Nullable a0);

// Addresses of the objects PythonKit compares against.
void *_Nonnull GaragePyKit__Py_ZeroStruct(void);
void *_Nonnull GaragePyKit__Py_TrueStruct(void);
void *_Nonnull GaragePyKit_PyBool_Type(void);
void *_Nonnull GaragePyKit_PySlice_Type(void);

#endif  // GARAGE_PYTHONKIT_SYMBOLS_H
