//===-- GaragePythonLibrary.swift --------------------------------*- swift -*-===//
//
// Garage's replacement for PythonKit's PythonLibrary.swift and
// PythonLibrary+Symbols.swift (PythonKit is the ext/pythonkit/PythonKit
// submodule; its other sources are compiled as they are). Same names and types
// as upstream, but every symbol is bound at link time through
// GaragePythonKitSymbols instead of dlopen/dlsym. The data symbols use Python 3's
// objects (`_Py_ZeroStruct` is `Py_False`, which upstream's lookup never found)
// and the legacy names map to the Python 3 functions upstream picks on Python 3.
// Generated by tools/pythonkit/generate_symbols.py; do not edit.
//
//===----------------------------------------------------------------------===//

import GaragePythonKitSymbols

//===----------------------------------------------------------------------===//
// Required Python typealiases and constants.
//===----------------------------------------------------------------------===//

@usableFromInline
typealias PyObjectPointer = UnsafeMutableRawPointer
typealias PyMethodDefPointer = UnsafeMutableRawPointer
typealias PyCCharPointer = UnsafePointer<Int8>
typealias PyBinaryOperation =
    @convention(c) (PyObjectPointer?, PyObjectPointer?) -> PyObjectPointer?
typealias PyUnaryOperation =
    @convention(c) (PyObjectPointer?) -> PyObjectPointer?

let Py_LT: Int32 = 0
let Py_LE: Int32 = 1
let Py_EQ: Int32 = 2
let Py_NE: Int32 = 3
let Py_GT: Int32 = 4
let Py_GE: Int32 = 5

//===----------------------------------------------------------------------===//
//===----------------------------------------------------------------------===//
// Python library symbols, bound at link time.
//===----------------------------------------------------------------------===//

let Py_Initialize: @convention(c) () -> Void =
    GaragePyKit_Py_Initialize

let Py_IncRef: @convention(c) (PyObjectPointer?) -> Void =
    GaragePyKit_Py_IncRef

let Py_DecRef: @convention(c) (PyObjectPointer?) -> Void =
    GaragePyKit_Py_DecRef

let PyImport_ImportModule: @convention(c) (PyCCharPointer) -> PyObjectPointer? =
    GaragePyKit_PyImport_ImportModule

let PyEval_GetBuiltins: @convention(c) () -> PyObjectPointer =
    GaragePyKit_PyEval_GetBuiltins

let PyRun_SimpleString: @convention(c) (PyCCharPointer) -> Void =
    GaragePyKit_PyRun_SimpleString

let PyCFunction_NewEx: @convention(c) (PyMethodDefPointer, UnsafeMutableRawPointer, UnsafeMutableRawPointer?) -> PyObjectPointer =
    GaragePyKit_PyCFunction_NewEx

let PyInstanceMethod_New: @convention(c) (PyObjectPointer) -> PyObjectPointer =
    GaragePyKit_PyInstanceMethod_New

let PyCapsule_New: @convention(c) (UnsafeMutableRawPointer, UnsafePointer<CChar>?, OpaquePointer) -> PyObjectPointer =
    GaragePyKit_PyCapsule_New

let PyCapsule_GetPointer: @convention(c) (PyObjectPointer?, UnsafePointer<CChar>?) -> UnsafeMutableRawPointer =
    GaragePyKit_PyCapsule_GetPointer

let PyErr_SetString: @convention(c) (PyObjectPointer, UnsafePointer<CChar>?) -> Void =
    GaragePyKit_PyErr_SetString

let PyErr_Occurred: @convention(c) () -> PyObjectPointer? =
    GaragePyKit_PyErr_Occurred

let PyErr_Clear: @convention(c) () -> Void =
    GaragePyKit_PyErr_Clear

let PyErr_Fetch: @convention(c) (UnsafeMutablePointer<PyObjectPointer?>, UnsafeMutablePointer<PyObjectPointer?>, UnsafeMutablePointer<PyObjectPointer?>) -> Void =
    GaragePyKit_PyErr_Fetch

let PyDict_New: @convention(c) () -> PyObjectPointer? =
    GaragePyKit_PyDict_New

let PyDict_Contains: @convention(c) (PyObjectPointer?, PyObjectPointer?) -> Int32 =
    GaragePyKit_PyDict_Contains

let PyDict_SetItem: @convention(c) (PyObjectPointer?, PyObjectPointer, PyObjectPointer) -> Void =
    GaragePyKit_PyDict_SetItem

let PyObject_GetItem: @convention(c) (PyObjectPointer, PyObjectPointer) -> PyObjectPointer? =
    GaragePyKit_PyObject_GetItem

let PyObject_SetItem: @convention(c) (PyObjectPointer, PyObjectPointer, PyObjectPointer) -> Void =
    GaragePyKit_PyObject_SetItem

let PyObject_DelItem: @convention(c) (PyObjectPointer, PyObjectPointer) -> Void =
    GaragePyKit_PyObject_DelItem

let PyObject_Call: @convention(c) (PyObjectPointer, PyObjectPointer, PyObjectPointer?) -> PyObjectPointer? =
    GaragePyKit_PyObject_Call

let PyObject_CallObject: @convention(c) (PyObjectPointer, PyObjectPointer) -> PyObjectPointer? =
    GaragePyKit_PyObject_CallObject

let PyObject_GetAttrString: @convention(c) (PyObjectPointer, PyCCharPointer) -> PyObjectPointer? =
    GaragePyKit_PyObject_GetAttrString

let PyObject_SetAttrString: @convention(c) (PyObjectPointer, PyCCharPointer, PyObjectPointer) -> Int32 =
    GaragePyKit_PyObject_SetAttrString

let PySlice_New: @convention(c) (PyObjectPointer?, PyObjectPointer?, PyObjectPointer?) -> PyObjectPointer? =
    GaragePyKit_PySlice_New

let PyTuple_New: @convention(c) (Int) -> PyObjectPointer? =
    GaragePyKit_PyTuple_New

let PyTuple_SetItem: @convention(c) (PyObjectPointer, Int, PyObjectPointer) -> Void =
    GaragePyKit_PyTuple_SetItem

let PyObject_RichCompare: @convention(c) (PyObjectPointer, PyObjectPointer, Int32) -> PyObjectPointer? =
    GaragePyKit_PyObject_RichCompare

let PyObject_RichCompareBool: @convention(c) (PyObjectPointer, PyObjectPointer, Int32) -> Int32 =
    GaragePyKit_PyObject_RichCompareBool

let PyDict_Next: @convention(c) (PyObjectPointer, UnsafeMutablePointer<Int>, UnsafeMutablePointer<PyObjectPointer?>, UnsafeMutablePointer<PyObjectPointer?>) -> Int32 =
    GaragePyKit_PyDict_Next

let PyIter_Next: @convention(c) (PyObjectPointer) -> PyObjectPointer? =
    GaragePyKit_PyIter_Next

let PyObject_GetIter: @convention(c) (PyObjectPointer) -> PyObjectPointer? =
    GaragePyKit_PyObject_GetIter

let PyList_New: @convention(c) (Int) -> PyObjectPointer? =
    GaragePyKit_PyList_New

let PyList_SetItem: @convention(c) (PyObjectPointer, Int, PyObjectPointer) -> Int32 =
    GaragePyKit_PyList_SetItem

let PyBool_FromLong: @convention(c) (Int) -> PyObjectPointer =
    GaragePyKit_PyBool_FromLong

let PyFloat_AsDouble: @convention(c) (PyObjectPointer) -> Double =
    GaragePyKit_PyFloat_AsDouble

let PyFloat_FromDouble: @convention(c) (Double) -> PyObjectPointer =
    GaragePyKit_PyFloat_FromDouble

let PyInt_AsLong: @convention(c) (PyObjectPointer) -> Int =
    GaragePyKit_PyInt_AsLong

let PyInt_FromLong: @convention(c) (Int) -> PyObjectPointer =
    GaragePyKit_PyInt_FromLong

let PyInt_AsUnsignedLongMask: @convention(c) (PyObjectPointer) -> UInt =
    GaragePyKit_PyInt_AsUnsignedLongMask

let PyInt_FromSize_t: @convention(c) (UInt) -> PyObjectPointer =
    GaragePyKit_PyInt_FromSize_t

let PyString_AsString: @convention(c) (PyObjectPointer) -> PyCCharPointer? =
    GaragePyKit_PyString_AsString

let PyString_FromStringAndSize: @convention(c) (PyCCharPointer?, Int) -> (PyObjectPointer?) =
    GaragePyKit_PyString_FromStringAndSize

let PyBytes_FromStringAndSize: @convention(c) (PyCCharPointer?, Int) -> (PyObjectPointer?) =
    GaragePyKit_PyBytes_FromStringAndSize

let PyBytes_AsStringAndSize: @convention(c) (PyObjectPointer, UnsafeMutablePointer<UnsafeMutablePointer<CChar>?>?, UnsafeMutablePointer<Int>?) -> CInt =
    GaragePyKit_PyBytes_AsStringAndSize

let PyNumber_Add: PyBinaryOperation =
    GaragePyKit_PyNumber_Add

let PyNumber_Subtract: PyBinaryOperation =
    GaragePyKit_PyNumber_Subtract

let PyNumber_Multiply: PyBinaryOperation =
    GaragePyKit_PyNumber_Multiply

let PyNumber_TrueDivide: PyBinaryOperation =
    GaragePyKit_PyNumber_TrueDivide

let PyNumber_InPlaceAdd: PyBinaryOperation =
    GaragePyKit_PyNumber_InPlaceAdd

let PyNumber_InPlaceSubtract: PyBinaryOperation =
    GaragePyKit_PyNumber_InPlaceSubtract

let PyNumber_InPlaceMultiply: PyBinaryOperation =
    GaragePyKit_PyNumber_InPlaceMultiply

let PyNumber_InPlaceTrueDivide: PyBinaryOperation =
    GaragePyKit_PyNumber_InPlaceTrueDivide

let PyNumber_Negative: PyUnaryOperation =
    GaragePyKit_PyNumber_Negative

let PyNumber_And: PyBinaryOperation =
    GaragePyKit_PyNumber_And

let PyNumber_Or: PyBinaryOperation =
    GaragePyKit_PyNumber_Or

let PyNumber_Xor: PyBinaryOperation =
    GaragePyKit_PyNumber_Xor

let PyNumber_InPlaceAnd: PyBinaryOperation =
    GaragePyKit_PyNumber_InPlaceAnd

let PyNumber_InPlaceOr: PyBinaryOperation =
    GaragePyKit_PyNumber_InPlaceOr

let PyNumber_InPlaceXor: PyBinaryOperation =
    GaragePyKit_PyNumber_InPlaceXor

let PyNumber_Invert: PyUnaryOperation =
    GaragePyKit_PyNumber_Invert

var _Py_ZeroStruct: PyObjectPointer { GaragePyKit__Py_ZeroStruct() }

var _Py_TrueStruct: PyObjectPointer { GaragePyKit__Py_TrueStruct() }

var PyBool_Type: PyObjectPointer { GaragePyKit_PyBool_Type() }

var PySlice_Type: PyObjectPointer { GaragePyKit_PySlice_Type() }
