"""Generate PythonKit's link-time symbol table from the submodule's PythonLibrary+Symbols.swift.

Writes ext/pythonkit/GaragePythonLibrary.swift and ext/pythonkit/symbols/GaragePythonKitSymbols.{h,c}.
Run it after moving the ext/pythonkit/PythonKit submodule to another tag:

    python3 tools/pythonkit/generate_symbols.py          # rewrite the files
    python3 tools/pythonkit/generate_symbols.py --check  # exit 1 when they are out of date
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PYTHONKIT = ROOT / "ext/pythonkit"
UPSTREAM = PYTHONKIT / "PythonKit/PythonKit/PythonLibrary+Symbols.swift"

# PythonKit's Swift types and the C types its symbols are declared with here.
C_TYPES = {
    "PyObjectPointer": "void *_Nonnull",
    "PyObjectPointer?": "void *_Nullable",
    "PyMethodDefPointer": "void *_Nonnull",
    "UnsafeMutableRawPointer": "void *_Nonnull",
    "UnsafeMutableRawPointer?": "void *_Nullable",
    "PyCCharPointer": "const char *_Nonnull",
    "PyCCharPointer?": "const char *_Nullable",
    "UnsafePointer<CChar>?": "const char *_Nullable",
    "OpaquePointer": "struct GaragePyKitOpaque *_Nonnull",
    "Int": "long",
    "UInt": "unsigned long",
    "Int32": "int",
    "CInt": "int",
    "Double": "double",
    "Void": "void",
    "UnsafeMutablePointer<Int>": "long *_Nonnull",
    "UnsafeMutablePointer<Int>?": "long *_Nullable",
    "UnsafeMutablePointer<PyObjectPointer?>": "void *_Nullable *_Nonnull",
    "UnsafeMutablePointer<UnsafeMutablePointer<CChar>?>?": "char *_Nullable *_Nullable",
}
# Casts from those C types to the ones CPython's own prototypes take.
CASTS = {
    "void *_Nullable *_Nonnull": "(PyObject **)",
    "long *_Nonnull": "(Py_ssize_t *)",
    "long *_Nullable": "(Py_ssize_t *)",
    "struct GaragePyKitOpaque *_Nonnull": "(PyCapsule_Destructor)(void *)",
}
# Data symbols, by the C expression for their address. `_Py_ZeroStruct` is Python 2's name for
# False, which upstream's lookup never finds on Python 3.
DATA = {
    "_Py_ZeroStruct": "Py_False",
    "_Py_TrueStruct": "Py_True",
    "PyBool_Type": "(void *)&PyBool_Type",
    "PySlice_Type": "(void *)&PySlice_Type",
}
# Extra trailing arguments: PythonKit declares PyUnicode_DecodeUTF8 without its `errors` argument.
EXTRA_ARGS = {"PyString_FromStringAndSize": ["NULL"]}

BANNER = """\
//===----------------------------------------------------------------------===//
// Garage: link-time binding for PythonKit (ext/pythonkit/PythonKit, a submodule).
// Generated by tools/pythonkit/generate_symbols.py; do not edit.
//
// Upstream PythonKit dlopen()s the Python library and dlsym()s every C-API
// function it calls. Garage always links the bundled Python.framework, so this
// replaces PythonLibrary.swift and PythonLibrary+Symbols.swift: each symbol is a
// plain C function here, resolved by the static linker and bound by dyld at load
// time, with no dlopen or dlsym.
//===----------------------------------------------------------------------===//
"""


def _split_arguments(text: str) -> list[str]:
    parts, depth, current = [], 0, ""
    for char in text:
        if char in "<(":
            depth += 1
        elif char in ">)":
            depth -= 1
        if char == "," and depth == 0:
            parts.append(current.strip())
            current = ""
        else:
            current += char
    if current.strip():
        parts.append(current.strip())
    return parts


def generate() -> dict[Path, str]:
    source = UPSTREAM.read_text()
    head, body = source.split("// Python library symbols lazily loaded at runtime.")
    preamble = head.split("// Required Python", 1)[1]
    entries = re.findall(r'let (\w+):(.*?)=\s*PythonLibrary\.loadSymbol\(\s*name: "(\w+)"', body, re.DOTALL)

    header = [
        BANNER,
        "#ifndef GARAGE_PYTHONKIT_SYMBOLS_H",
        "#define GARAGE_PYTHONKIT_SYMBOLS_H",
        "",
        "// The types are PythonKit's (opaque pointers), not CPython's, so this header never",
        "// includes Python.h and nothing that imports it sees CPython's own declarations.",
        "",
        "struct GaragePyKitOpaque;",
        "",
    ]
    implementation = [BANNER, "#include <Python.h>", "", '#include "GaragePythonKitSymbols.h"', ""]
    swift = []
    data = []
    for name, swift_type, symbol in entries:
        swift_type = " ".join(swift_type.split()).replace("@convention(c) ( ", "@convention(c) (")
        if swift_type == "PyObjectPointer":
            data.append(name)
            continue
        if swift_type in ("PyBinaryOperation", "PyUnaryOperation"):
            arguments = ["PyObjectPointer?"] * (2 if swift_type == "PyBinaryOperation" else 1)
            result = "PyObjectPointer?"
        else:
            match = re.fullmatch(r"@convention\(c\) \((.*)\) -> (.*)", swift_type)
            if match is None:
                raise SystemExit(f"cannot parse the type of {name}: {swift_type}")
            arguments = _split_arguments(match.group(1))
            result = match.group(2).strip()
            if result.startswith("(") and result.endswith(")"):
                result = result[1:-1]
        c_arguments = [C_TYPES[argument] for argument in arguments]
        c_result = C_TYPES[result]
        parameters = ", ".join(f"{c_type} a{index}" for index, c_type in enumerate(c_arguments)) or "void"
        call_arguments = [CASTS.get(c_type, "") + f"a{index}" for index, c_type in enumerate(c_arguments)]
        call = f"{symbol}({', '.join(call_arguments + EXTRA_ARGS.get(name, []))})"
        statement = f"{call};" if c_result == "void" else f"return {call};"
        header.append(f"{c_result} GaragePyKit_{name}({parameters});")
        implementation.append(f"{c_result} GaragePyKit_{name}({parameters}) {{ {statement} }}")
        swift.append(f"let {name}: {swift_type} =\n    GaragePyKit_{name}\n")

    header += ["", "// Addresses of the objects PythonKit compares against."]
    implementation.append("")
    for name in data:
        header.append(f"void *_Nonnull GaragePyKit_{name}(void);")
        implementation.append(f"void *_Nonnull GaragePyKit_{name}(void) {{ return {DATA[name]}; }}")
        swift.append(f"var {name}: PyObjectPointer {{ GaragePyKit_{name}() }}\n")
    header += ["", "#endif  // GARAGE_PYTHONKIT_SYMBOLS_H", ""]

    swift_file = (
        "//===-- GaragePythonLibrary.swift --------------------------------*- swift -*-===//\n"
        "//\n"
        "// Garage's replacement for PythonKit's PythonLibrary.swift and\n"
        "// PythonLibrary+Symbols.swift (PythonKit is the ext/pythonkit/PythonKit\n"
        "// submodule; its other sources are compiled as they are). Same names and types\n"
        "// as upstream, but every symbol is bound at link time through\n"
        "// GaragePythonKitSymbols instead of dlopen/dlsym. The data symbols use Python 3's\n"
        "// objects (`_Py_ZeroStruct` is `Py_False`, which upstream's lookup never found)\n"
        "// and the legacy names map to the Python 3 functions upstream picks on Python 3.\n"
        "// Generated by tools/pythonkit/generate_symbols.py; do not edit.\n"
        "//\n"
        "//===----------------------------------------------------------------------===//\n"
        "\n"
        "import GaragePythonKitSymbols\n"
        "\n"
        "//===----------------------------------------------------------------------===//\n"
        f"// Required Python{preamble}"
        "//===----------------------------------------------------------------------===//\n"
        "// Python library symbols, bound at link time.\n"
        "//===----------------------------------------------------------------------===//\n"
        "\n" + "\n".join(swift).rstrip() + "\n"
    )
    return {
        PYTHONKIT / "GaragePythonLibrary.swift": swift_file,
        PYTHONKIT / "symbols/GaragePythonKitSymbols.h": "\n".join(header),
        PYTHONKIT / "symbols/GaragePythonKitSymbols.c": "\n".join(implementation) + "\n",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail when a generated file is out of date")
    arguments = parser.parse_args()
    if not UPSTREAM.is_file():
        print(f"{UPSTREAM.relative_to(ROOT)} is missing: run `git submodule update --init`", file=sys.stderr)
        return 1
    stale = []
    for path, text in generate().items():
        if path.exists() and path.read_text() == text:
            continue
        if arguments.check:
            stale.append(path.relative_to(ROOT))
        else:
            path.write_text(text)
    for path in stale:
        print(f"{path} is out of date: run python3 tools/pythonkit/generate_symbols.py", file=sys.stderr)
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
